Make an (almost) running version of sokoban
Running the game might result in “thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MismatchedDynamicOffsetCount { actual: 0, expected: 2 }'”. This is because of https://github.com/bevyengine/bevy/issues/134